import { SliderCaptcha } from "@slider-captcha-v2/react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const verifiedCallback = (token: any) => {
    console.log("Captcha token: " + token);
  };

  const toggleWrapperCard = () => {
    const captchaButton: HTMLElement = document.getElementsByClassName(
      "scaptcha-anchor-element"
    )[0] as HTMLElement;
    captchaButton.click();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={toggleWrapperCard}>Fire wrapper card</button>
        <SliderCaptcha
          create="api/create"
          verify="api/verify"
          callback={verifiedCallback}
          text={{
            anchor: "Click here to verify",
            challenge: "Verify",
          }}
          hasReloadButton
        />
      </main>
    </div>
  );
};

export default Home;
