import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SliderCaptcha from "@slider-captcha/react";

const Home: NextPage = () => {
  const verifiedCallback = (token: any) => {
    console.log("Captcha token: " + token);
  };

  const toggleWrapperCard = () => {
    const captchaButton: HTMLElement = document.getElementsByClassName(
      "scaptcha-anchor-element"
    )[0] as HTMLElement;
    captchaButton.click();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={toggleWrapperCard}>Fire wrapper card</button>
        <div className="captcha-wrapper">
          <SliderCaptcha
            create="api/create"
            verify="api/verify"
            callback={verifiedCallback}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
